### ISSUE TITLE
如何理解goroutine票池接口

### ISSUE THREAD

**Issue by OctopusLian** [OctopusLian/Load-Generator#7]
```go
type GoTickets interface {
	// 拿走一张票。
	Take()
	// 归还一张票。
	Return()
	// 票池是否已被激活。
	Active() bool
	// 票的总数。
	Total() uint32
	// 剩余的票数。
	Remainder() uint32
}
```

**Comment by wellttllew** [comment]
这个是多线程里面最常用的两种同步机制之一，你看到的这个叫做 semaphore： https://github.com/tmrts/go-patterns/blob/master/synchronization/semaphore.md

**Comment by OctopusLian** [comment]
好的，多谢答疑！
我理解为 票 == 程序为了启用一个`goroutine`而必须持有的一种令牌，或者称为权限。所以`goroutine`票池相当于真实地展示出一个程序正在运行的`goroutine`的数量。

**Comment by OctopusLian** [comment]
也可以把`goroutine`票池看成一个POSIX标准中描述的多值信号量。一个POSIX多值信号量的值代表了可用资源的数量，资源使用方获得或归还资源时会及时减小或增大该信号量的值，以便其他使用放实时了解资源的使用情况。  
在该值被减至0之后，所有试图减少该值的程序都会为此而阻塞。而当该值重新增至一个正整数的时候，这些程序就都会被唤醒。  
`lib.GoTickets`接口的`Take`方法和`Return`方法分别对应了多值信号量上的减一操作和增一操作。
